### ISSUE TITLE
Allocating space for the picker and how do I close it?

### ISSUE THREAD

**Issue by newlegendmedia** [unumotors/cordova-plugin-inline-datepicker#2]
I am able to get it to display but it doesn't show any controls for closing the picker and I have to leave a lot of space for it before it comes up.

Do you have any working example of the plugin? Your sample code helped but its not complete and you have a typo in the date callback - local should be locale in the function name.

Thanks!

**Comment by mihriminaz** [comment]
HTML is like this:

```
<div class="form-row">            
  <div class="form-input user-data-date user-data-date-from">
    <label class="form-inline-label">From<div class="pull-right date-from"></div></label>
    <div class="user-data-date-input"></div>
  </div>
  <div class="form-input user-data-date user-data-date-until">
    <label class="form-inline-label">Until<div class="pull-right date-until"></div></label>
    <div class="user-data-date-input"></div>
  </div>
</div>
```

And when we create the picker by sending the element div to insert the picker: 
(also another create call for .user-data-date-until)

````
cordova.plugins.DatePicker.create(
  this.$('.user-data-date-from .user-data-date-input'),
  {
    'id': 'user-data-date-from',
    'isHidden': true,
    'mode': cordova.plugins.DatePicker.Mode.DATE_AND_TIME,
    'date': this.fromDate,
    'minimumDate': todayMidnight,
    'minuteInterval': 10
  },
  (data) => { // valueChanged triggering
    this.dateFrom = new Date(data && data['date']);
  }
);
````

We added tap action to '.user-data-date-from' and '.user-data-date-until' divs so when they (row) are clicked we get the div of the picker -> 
        `var $input = $row.querySelector('.user-data-date-input');`

(you can also directly reach the element and send it in the show/hide function)

Show/hide is like: 
`cordova.plugins.DatePicker.show($input);`
`cordova.plugins.DatePicker.hide($input);`

**Comment by newlegendmedia** [comment]
Thanks! that is helpful. However, I am still not understanding how the user closes the picker when they are done selecting a date. It seems maybe that is up to me to put some sort of "done" button to close the picker?

**Comment by mihriminaz** [comment]
There is no automatically triggering for closing the picker. You can either set it on valueChanged callback as 
```
(data)=> { // valueChanged triggering
    this.dateFrom = new Date(data && data['date']);
    cordova.plugins.DatePicker.hide($input);
}
```
or have another way of UX. (in our case we have 2 buttons for from/until) so pickers are hidden at the initial state-> when from (or until button) is clicked until (or from) picker is hidden and from (or until) picker is shown.. and unless user clicks/toggle one more time to hide they are shown.

**Comment by newlegendmedia** [comment]
Thanks, I wound up working with the iOS standard picker and it seems to be working for me now. Appreciate your help!
