### ISSUE TITLE
Type cast bug in DatePickerManager

### ISSUE THREAD

**Issue by sajoneri** [unumotors/cordova-plugin-inline-datepicker#3]
Hi!
There seems to be a type cast bug in DatePickerManager.
DatePickerChanged notification in the DatePicker class sends timestamp in ms, defined as Int64
DatePickerManager::onChange then casts notification.userInfo?["date"] to Int, thus causing it to return 0.

Changing the line to
`let timestamp = (notification.userInfo?["date"] as? Int64) ?? 0`
should fix the problem.

Thank you for a very practical plugin!
/ jonas

**Comment by mihriminaz** [comment]
@sajoneri & @fiso thanks for your contributions.

**Comment by fiso** [comment]
Thanks for the excellent plugin!

**Comment by fiso** [comment]
Any chance you could push a release onto npm?

**Comment by cakuki** [comment]
Version 0.3.1 has been published. But it may take some time to be reflected on api & npm interface (due to their caching).

And thanks again for your contribution @fiso.
